import numpy as np
import matplotlib.pyplot as plt
import argparse
import os

def smooth_curve(points, factor=0.9):
    smoothed_points = []
    for point in points:
        if smoothed_points:
            previous = smoothed_points[-1]
            smoothed_points.append(previous * factor + point * (1 - factor))
        else:
            smoothed_points.append(point)
    return smoothed_points

def main():
    parser = argparse.ArgumentParser(description="Visualize UCB dominance over time from npz logs")
    parser.add_argument("--npz_file", type=str, required=True, help="Path to the npz file generated by run_dataset_step.py")
    parser.add_argument("--window_size", type=int, default=100, help="Sliding window size (rounds) to compute percentages")
    args = parser.parse_args()

    if not os.path.exists(args.npz_file):
        print(f"[ERROR] File not found: {args.npz_file}")
        return

    data = np.load(args.npz_file, allow_pickle=True)
    if "history_min_source" not in data.files:
        print("[ERROR] 'history_min_source' not found in the npz file. Please re-run the experiment first.")
        return

    sources = data["history_min_source"]
    n_rounds = len(sources)

    # We will use a sliding window to compute the percentage of each source
    w = args.window_size
    s1_pct = []
    s2_pct = []
    s3_pct = []
    steps = []

    for i in range(n_rounds - w + 1):
        window = sources[i:i+w]
        counts = { 's1': 0, 's2': 0, 's3': 0 }
        for s in window:
            if s in counts:
                counts[s] += 1
        
        s1_pct.append(counts['s1'] / w * 100)
        s2_pct.append(counts['s2'] / w * 100)
        s3_pct.append(counts['s3'] / w * 100)
        steps.append(i + w)

    fig, ax = plt.subplots(figsize=(10, 6))

    ax.plot(steps, smooth_curve(s1_pct, factor=0.8), label='S1 (Neural-LinUCB)', color='#1f77b4', lw=2)
    ax.plot(steps, smooth_curve(s2_pct, factor=0.8), label='S2 (UCB1)', color='#ff7f0e', lw=2)
    ax.plot(steps, smooth_curve(s3_pct, factor=0.8), label='S3 (LLM)', color='#2ca02c', lw=2)

    ax.set_xlabel("Time Step (Rounds)", fontsize=13)
    ax.set_ylabel(f"Selection Percentage (Window = {w})", fontsize=13)
    ax.set_title(f"Dynamic UCB Dominance ({os.path.basename(args.npz_file)})", fontsize=14, fontweight="bold")
    ax.legend(fontsize=11)
    ax.grid(True, linestyle='--', alpha=0.5)

    base_name = os.path.basename(args.npz_file).replace('.npz', '')
    out_dir = os.path.dirname(args.npz_file)
    out_path = os.path.join(out_dir, f"{base_name}_dominance_curve.png")
    
    fig.tight_layout()
    fig.savefig(out_path, dpi=300)
    plt.close(fig)
    print(f"Dominance visualization saved to: {out_path}")

if __name__ == "__main__":
    main()
